spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=oracle-client-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.transport=stdio
spring.ai.mcp.server.annotation-scanner.base-packages=com.example

spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.file.name=/tmp/oracle-client-mcp.log

mcp.db.connection.type=secretsmanager
mcp.db.connection.detail=arn:aws:secretsmanager:us-west-2:111709976242:secret:oracle-admin