# Spring AI MCP Server Configuration
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=pg-client-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.transport=sse
spring.ai.mcp.server.annotation-scanner.base-packages=com.example

server.port=9081

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4LaeSHWmZ
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4LaeSHWmZ/.well-known/jwks.json

# Database Configuration
mcp.db.connection.type=secretsmanager
mcp.db.connection.detail=arn:aws:secretsmanager:us-east-1:940597661534:secret:MMA-secret-aurora-admin-jltAyT
mcp.db.connection.readonly=false
mcp.db.testcase.readonly=false

logging.level.root=INFO
logging.level.com.example=DEBUG
