# OMA SC MCP Configuration
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=oma-sc-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.transport=sse
spring.ai.mcp.server.annotation-scanner.base-packages=com.example

server.port=9080

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4LaeSHWmZ
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4LaeSHWmZ/.well-known/jwks.json

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.security=DEBUG

oma.sc.default.s3path=s3://mma-dms-sc-006807303219/dms-sc-migration-project/ORACLE_AURORA_POSTGRESQL_2026-02-16T16-56-51.835Z.zip
